// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKMRr4vb2C05eS-GRpDg3jRJjWd188vJU',
    appId: '1:53409765369:web:e0cba35fab4810ed340f28',
    messagingSenderId: '53409765369',
    projectId: 'cbtdrktv',
    authDomain: 'cbtdrktv.firebaseapp.com',
    storageBucket: 'cbtdrktv.firebasestorage.app',
    measurementId: 'G-XW2N353N0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD86us9d9DqSmHuGRSITJKorboTfB59Mt8',
    appId: '1:53409765369:android:bf35004c5fc746e2340f28',
    messagingSenderId: '53409765369',
    projectId: 'cbtdrktv',
    storageBucket: 'cbtdrktv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN75MxBKpybwCFNIN0oLci6TdjU7KDiFg',
    appId: '1:53409765369:ios:9df85d2405ee6767340f28',
    messagingSenderId: '53409765369',
    projectId: 'cbtdrktv',
    storageBucket: 'cbtdrktv.firebasestorage.app',
    iosClientId: '53409765369-6cdvchn5127b9tct7994mcdmogdvgsn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cbtDrktv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN75MxBKpybwCFNIN0oLci6TdjU7KDiFg',
    appId: '1:53409765369:ios:9df85d2405ee6767340f28',
    messagingSenderId: '53409765369',
    projectId: 'cbtdrktv',
    storageBucket: 'cbtdrktv.firebasestorage.app',
    iosClientId: '53409765369-6cdvchn5127b9tct7994mcdmogdvgsn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cbtDrktv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKMRr4vb2C05eS-GRpDg3jRJjWd188vJU',
    appId: '1:53409765369:web:a07feae34116c736340f28',
    messagingSenderId: '53409765369',
    projectId: 'cbtdrktv',
    authDomain: 'cbtdrktv.firebaseapp.com',
    storageBucket: 'cbtdrktv.firebasestorage.app',
    measurementId: 'G-2L2CNHFHKL',
  );
}
